// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `to_core_category`, `to_core_region`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// Calculate tax
///
/// `price` - DECIMAL(20,6) string, e.g. "99.9900000"
/// `custom_rate` - optional ovveride fraction, e.g. "0.0750000"; pass "" for default
///
/// Called from dart as:
/// ```dart
/// final result = await calculateTax(
///   price: '99.990000',
///   region: Region.eu,
///   category: Category.digital,
///   customRate: '',
/// );
///
/// ```
Future<TaxBreakdown> calculateTax(
        {required String price,
        required Region region,
        required Category category,
        required String customRate}) =>
    RustLib.instance.api.crateApiTaxCalculateTax(
        price: price,
        region: region,
        category: category,
        customRate: customRate);

/// Get the effective rate for a region+category as a DECIMAL(20,6) string.
/// e.g. "0.200000" for EU/Digital.
String getEffectiveRate({required Region region, required Category category}) =>
    RustLib.instance.api
        .crateApiTaxGetEffectiveRate(region: region, category: category);

enum Category {
  general,
  food,
  medicine,
  digital,
  luxury,
  ;
}

enum Region {
  us,
  eu,
  uk,
  au,
  custom,
  ;
}

/// Tax breakdown returned to Dart.
/// All monetary fields are DECIMAL(20,6) strings, e.g. "99.990000".
class TaxBreakdown {
  final String priceBeforeTax;
  final String rate;
  final String ratePercent;
  final String taxAmount;
  final String priceAfterTax;
  final String currency;
  final String regionDisplay;
  final String categoryDisplay;

  const TaxBreakdown({
    required this.priceBeforeTax,
    required this.rate,
    required this.ratePercent,
    required this.taxAmount,
    required this.priceAfterTax,
    required this.currency,
    required this.regionDisplay,
    required this.categoryDisplay,
  });

  @override
  int get hashCode =>
      priceBeforeTax.hashCode ^
      rate.hashCode ^
      ratePercent.hashCode ^
      taxAmount.hashCode ^
      priceAfterTax.hashCode ^
      currency.hashCode ^
      regionDisplay.hashCode ^
      categoryDisplay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaxBreakdown &&
          runtimeType == other.runtimeType &&
          priceBeforeTax == other.priceBeforeTax &&
          rate == other.rate &&
          ratePercent == other.ratePercent &&
          taxAmount == other.taxAmount &&
          priceAfterTax == other.priceAfterTax &&
          currency == other.currency &&
          regionDisplay == other.regionDisplay &&
          categoryDisplay == other.categoryDisplay;
}
