import 'product.dart';

final List<Product> mockProducts = [
  Product(
    id: 1,
    name: 'Nasi Goreng Spesial',
    category: 'Food',
    price: 35000,
    unit: 'pcs',
    taxSetting: TaxSetting.taxInclusive,
    taxRate: 11,
    taxId: 'indonesia_pb11%.id',
    emoji: '🍳',
  ),
  Product(
    id: 2,
    name: 'Es Teh Manis',
    category: 'Drink',
    price: 8000,
    unit: 'pcs',
    taxSetting: TaxSetting.taxExclusive,
    taxRate: 10,
    taxId: 'indonesia_pb10%.id',
    emoji: '🧋',
  ),
  Product(
    id: 3,
    name: 'Ayam Bakar',
    category: 'Food',
    price: 45000,
    unit: 'pcs',
    taxSetting: TaxSetting.taxInclusive,
    taxRate: 11,
    taxId: 'indonesia_pb11%.id',
    emoji: '🍗',
  ),
  Product(
    id: 4,
    name: 'Mineral Water',
    category: 'Drink',
    price: 5000,
    unit: 'pcs',
    taxSetting: TaxSetting.noTax,
    taxRate: 0,
    taxId: null,
    emoji: '💧',
  ),
  Product(
    id: 5,
    name: 'Mie Goreng',
    category: 'Food',
    price: 28000,
    unit: 'pcs',
    taxSetting: TaxSetting.taxExclusive,
    taxRate: 11,
    taxId: 'indonesia_pb11%.id',
    emoji: '🍜',
  ),
  Product(
    id: 6,
    name: 'Kopi Hitam',
    category: 'Drink',
    price: 12000,
    unit: 'pcs',
    taxSetting: TaxSetting.taxExclusive,
    taxRate: 10,
    taxId: 'indonesia_pb10%.id',
    emoji: '☕',
  ),
  Product(
    id: 7,
    name: 'Pisang Goreng',
    category: 'Snack',
    price: 15000,
    unit: 'pcs',
    taxSetting: TaxSetting.taxInclusive,
    taxRate: 10,
    taxId: 'indonesia_pb10%.id',
    emoji: '🍌',
  ),
  Product(
    id: 8,
    name: 'Juice Alpukat',
    category: 'Drink',
    price: 20000,
    unit: 'pcs',
    taxSetting: TaxSetting.noTax,
    taxRate: 0,
    taxId: null,
    emoji: '🥑',
  ),
];